name: Build and Deploy Code

on: [push, pull_request]
  # push:
  #   branches:
  #     - "main"
  # pull_request:
  #   branches:
  #     - "test_main"

jobs:
  job1:
    environment: testing
    env:
      DATABASE_HOSTNAME: ${{secrets.DATABASE_HOSTNAME}}
      DATABASE_PORT: ${{secrets.DATABASE_PORT}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
      DATABASE_NAME: ${{secrets.DATABASE_NAME}}
      DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      ALGORITHM: ${{secrets.ALGORITHM}}
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    # services:
    #   mysql:
    #     image: mysql:latest
    #     env:
    #       MYSQL_HOST: ${{secrets.DATABASE_HOSTNAME}}
    #       MYSQL_USER: ${{secrets.DATABASE_USERNAME}}
    #       MYSQL_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
    #       MYSQL_DATABASE: ${{secrets.DATABASE_NAME}}_test
    #       MYSQL_ROOT_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
    #     ports:
    #       - 3306:3306
    #     options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    runs-on: ubuntu-latest
    steps:
      - name: set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{secrets.DATABASE_NAME}}_test;' -u${{secrets.DATABASE_USERNAME}} -p${{secrets.DATABASE_PASSWORD}}
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: installing python v3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt
      - name: test with pytest
        run: |
          pip install pytest
          pytest