name: Build and Deploy Code

on: [push, pull_request]
  # push:
  #   branches:
  #     - "main"
  # pull_request:
  #   branches:
  #     - "test_main"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: custom step
        run: echo "custom step test"
